name: Gitleaks Secret Scan

on: push

jobs:
  secret_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          wget -qO - https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz | tar xz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        id: gitleaks_scan
        continue-on-error: true  # This allows the job to continue even if secrets are found
        run: |
          gitleaks detect --source=. --verbose || true  # Ensures it doesn't break the workflow

      - name: Notify Discord if secrets found
        if: steps.gitleaks_scan.outcome == 'failure' && env.DISCORD_WEBHOOK != ''
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST -d '{"username": "Gitleaks Bot", "content": "⚠️ **Gitleaks Alert**: Secrets detected!\nCheck GitHub Actions logs: https://github.com/SirZeus-Sec/Gitleaks-test-CI/actions"}' \
          $DISCORD_WEBHOOK
